version: "3.8"

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: kspon-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: kspon
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - kspon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sports_data_lab -d sports_data_lab"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7.2-alpine
    container_name: kspon-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kspon-network
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass sports_data_lab
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "sports_data_lab", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  kspon-network:
    driver: bridge
